---
- name: Simple CI/CD Deployment
  hosts: web
  become: no
  tasks:
    - name: Ensure app folder exists
      file:
        path: /home/vagrant/sample-app
        state: directory
        mode: 0755

    - name: Pull latest code from GitHub
      git:
        repo: 'https://github.com/tarakantaacharya/devops-lab.git'
        dest: /home/vagrant/sample-app
        version: main
        force: yes

    - name: Display deployment success
      debug:
        msg: "✅ Code pulled successfully to /home/vagrant/sample-app"
