name: Simple CI/CD with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.VM_HOST }}" > ~/.ssh/known_hosts

      - name: Deploy to VM using Ansible
        run: |
          ansible-playbook -i hosts.ini deploy.yml \
            --key-file ~/.ssh/id_ed25519 \
            -u vagrant
